export const state = {
  currentModel: 'Llama-3-70B',
  chartRegistry: [],
  savedStrategies: [],
  simResults: [],
  simInput: null,
  simRunning: false,
  sensitivityRunning: false,
  crossRunning: false,
  workloadSource: 'synthetic',
  strategyMode: 'dsl',
  simCache: {},
  sensExportState: null,
  sensCache: {},
  sensPointCache: {},
  sensSnapshots: [],
};
